### ISSUE TITLE
Seems not compatible with cdk 1.81.0

### ISSUE THREAD

**Issue by readybuilderone** [pahud/cdk-kubesphere#7]
I create the cdk project using projen.
since the version of "npx projen" is 1.81.0, so I set the  cdkVersion to 1.81.0 in .projenrc.js as well.

```
const { AwsCdkTypeScriptApp } = require('projen');

const project = new AwsCdkTypeScriptApp({
  cdkVersion: '1.81.0',
  name: 'kubesphere-cdk',
  cdkDependencies:[
    'cdk-kubesphere@0.0.7',
    '@aws-cdk/aws-ec2',
  ]
});

project.synth();
```

I used the sample code in main.ts as following:
```
import { App, Construct, Stack, StackProps } from '@aws-cdk/core';
import { KubeSphere } from 'cdk-kubesphere';

export class MyStack extends Stack {
  constructor(scope: Construct, id: string, props: StackProps = {}) {
    super(scope, id, props);

    // define resources here...
    new KubeSphere(this, 'sample');
  }
}
```

Then I run into the error:
> Argument of type 'this' is not assignable to parameter of type 'Construct'.
  Type 'MyStack' is not assignable to type 'Construct'.

I did some research, and found this issue: https://github.com/aws/aws-cdk/issues/7280 
I tried to delete the node_modules and package.json and rerun "npx projen" to generate them, but still come with the same error.

**Comment by guan840912** [comment]
Try
does: [‘cdk-kubesphere@0.0.7’] ??

**Comment by pahud** [comment]
Thank you for your feedback. I just release cdk-kubesphere 0.0.8 with the [awscdk-81-patch](https://github.com/eladb/awscdk-81-patch) [built in the library](https://github.com/pahud/cdk-kubesphere/blob/6a5cd1ff82008a616133b48fe7fb74922d0d8951/src/kubesphere.ts#L4-L6). You don't have to do anything, just use the `0.0.8` and it should work with cdk 1.81.0

**Comment by readybuilderone** [comment]
thanks @pahud , the 0.0.8 works with 1.81.0 now.

This issue could be closed.
